### PR TITLE
Llvm 7 build

### PR DESCRIPTION
**Pull request by Aiethel**
Build for llvm-7 (and possibly others lower than 8) version fails because of some API changes. This PR tries to fix that.

### CODE REVIEW

**Review by pgoodman — APPROVED** [review]

**Comment by artemdinaburg** [comment]
@Aiethel it looks like CallSite has been removed in LLVM-11; relevant error:

```
/__w/remill/remill/lib/BC/DeadStoreEliminator.cpp:1191:20: error: no member named 'CallSite' in namespace 'llvm'
  auto val = llvm::CallSite(&inst).getCalledValue()->stripPointerCasts();
             ~~~~~~^
3 errors generated.
```

Its replacement is [AbstractCallSite](https://llvm.org/doxygen/classllvm_1_1AbstractCallSite.html) with a slightly different API. This would require hacking in some compatibility headers.

**Comment by Aiethel** [comment]
Yeah, I thought that `llvm::AbstractCallSite` was added along the original `llvm::CallSite`. 

I wrapped the compatibility class into `remill::compat::llvm` namespace to make the compatibility glue more easily recognizable.

**Comment by Aiethel** [comment]
Failing test case seems to be unrelated to the changes?

**Comment by ekilmer** [comment]
> Failing test case seems to be unrelated to the changes?

Yes, there is a flaky test on Mac, and the Mac OS 11.0 runners are very inconsistent. CI looks good!

**Pull request merged**
